[package]
name = "combination"
version = "0.6.0"
entrypoint = "lib.typ"
authors = ["Paul Mazaitis <paul@mazaitis.org>"]
license = "MIT"
description = "A package for creating subfigures with captions."
repository = "https://github.com/jomaway/typst-gentle-clues"
keywords = ["figures"]
categories = ["components", "visualization"]
compiler = "0.11.0"
exclude = ["docs.typ", "docs.pdf"]
